# Generated by Django 4.0.3 on 2022-03-31 15:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Avatar_of_choice',
            fields=[
                ('name', models.CharField(max_length=50, verbose_name='Название')),
                ('usr', models.OneToOneField(default='1', on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='chosen_avatar', serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('portrait', models.ImageField(upload_to='user_images/')),
                ('chr_class', models.CharField(blank=b'I01\n', max_length=13, null=b'I01\n')),
                ('xp', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('background', models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n')),
                ('diety', models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n')),
                ('origin', models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n')),
                ('worldview', models.CharField(blank=b'I01\n', max_length=2, null=b'I01\n')),
                ('attrib_strength', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('attrib_agility', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('attrib_charisma', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('attrib_endurance', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('attrib_intelligence', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('attrib_wisdom', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('armour_class', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('hp', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('speed', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_acrobatics', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_arcane', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_athletics', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_craft', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_decieve', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_diplomacy', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_intimidation', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_medicine', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_nature', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_occult', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_performance', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_religion', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_social', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_stealth', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_survival', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('skills_theft', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('save_reflex', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('save_resilience', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('save_will', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('weapon', models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n')),
                ('attack', models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n')),
                ('damage', models.CharField(blank=b'I01\n', max_length=100, null=b'I01\n')),
                ('attention', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('dc_class', models.IntegerField(blank=b'I01\n', null=b'I01\n')),
                ('notes', models.TextField(blank=b'I01\n', null=b'I01\n')),
                ('usr', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
