# Generated by Django 4.0.3 on 2022-03-31 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_character_portrait'),
    ]

    operations = [
        migrations.AddField(
            model_name='character',
            name='is_dying',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
        migrations.AddField(
            model_name='character',
            name='mortal_wounds',
            field=models.IntegerField(blank=b'I01\n', null=b'I01\n'),
            preserve_default=b'I01\n',
        ),
    ]
